services:
  - type: web
    name: your-app-name
    env: python
    buildCommand: |
      export CARGO_HOME=$XDG_CACHE_HOME/cargo
      curl https://sh.rustup.rs -sSf | sh -s -- -y --no-modify-path
      export PATH="$CARGO_HOME/bin:$PATH"
      pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10